N10 = int(input("Введите исходное 10-чное число"))
p = int(input("Введите основание системы"))
k = int(1)
Np=int(0)
while N10 !=0:
    Np = Np + (N10%p)*k
    k = k*10
    N10 = N10//p
print (f'N{p} = {Np}')
